### ISSUE TITLE
Bug: Water overlay continues to exist after dying in water

### ISSUE THREAD

**Issue by ShygalCoco** [StrataSource/Portal-2-Community-Edition#1466] opened 2023-07-30 15:31 UTC
### Describe the bug

When dying in water, the aquatic overlay that appears on the screen when underwater continues to exist after loading a save from death. Here's a video of it in action.
https://github.com/StrataSource/Portal-2-Community-Edition/assets/69723642/7a5d7518-d709-4984-86c8-46bcbbdbecbb

### Issue Map

I discovered this when playing on Rip Rip Rip's new Portal 1 Chamber 11 recreation that he posted in #beta-maps-share, though I wouldn't see why not this would happen in any other map with deadly water.

### To Reproduce

Just jump into deadly water and let the game load a save from death.

### Operating System

Windows 10

**Comment by tmob03** [comment] 2023-08-04 07:15
Duplicate of #1038

**Closed** 2023-08-04 07:16 UTC
Labels: Type: bug, What: Graphics
