### ISSUE TITLE
Rocket turret close animation bug

### ISSUE THREAD

**Issue by Teapottt** [StrataSource/Portal-2-Community-Edition#1569] opened 2023-11-03 09:27 UTC
### Describe the bug

When you disable the rocket turret it's close animation is bugged
https://www.youtube.com/watch?v=96lOnt3jQZ0

### Issue Map

https://drive.google.com/drive/folders/10z5pSy6PvVxqX8qXODizh-ye8QU_hqYD?usp=sharing

### To Reproduce

1. Open map "test.bsp"
2. Click the button nearest to the rocket turret to enable him
3. Click the other button to disable him

**Comment by Luke18033** [comment] 2023-11-03 09:32
Duplicate of #1206

**Closed by Luke18033** 2023-11-03 09:32 UTC
Labels: Type: bug
