### ISSUE TITLE
npc_barnacle is broken in multiplayer

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1398] opened 2023-06-24 17:18 UTC
### Describe the bug

Still can't grab players, tongue incorrect work, can't eat npcs (just kill and drop ragdolls), can't grab physics objects (not include ?ragdolls?).

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/179d2a8c-9ca9-4696-a89f-5f3895b7f62d

### Issue Map

Any in multiplayer.

### To Reproduce

1. Open any map in multiplayer.
2. Enter in console `sv_cheats 1; ent_create npc_barnacle`.
3. Experement with it like in the video.

### Operating System

Any.

**Comment by AWildErin** [comment] 2023-06-24 17:22
Essentially a duplicate of #1237, please comment on that issue with the issues from this.

**Closed by AWildErin** 2023-06-24 17:22 UTC
Labels: Type: bug

**Comment by MyGamepedia** [comment] 2023-06-24 17:29
> Essentially a duplicate of #1237, please comment on that issue with the issues from this.

Here problen not only about that it can't grab players.

**Comment by AWildErin** [comment] 2023-06-24 17:40
"please comment on that issue with the issues from this." It's easier to generally track 1 issue about barnacles than 2.
