### ISSUE TITLE
Bug: Scrolling down when in the particle editor brings you back to the main menu

### ISSUE THREAD

**Issue by Zepalesque** [StrataSource/Portal-2-Community-Edition#1236] opened 2023-04-07 16:47 UTC
### Describe the bug

When scrolling down with the mouse wheel while in the particle editor (or anywhere in the tools mode ui), it goes to the main menu. This happens even when the mouse isn't hovering over something that can be scrolled.

video:
https://user-images.githubusercontent.com/60141811/230646149-010d4cc7-cdef-4afe-8041-38584ebd9d00.mp4

### Issue Map

N/A - Occurs in Tools Mode UI

### To Reproduce

1: Open P2CE with -tools in the arguments
2: Press F10 to open the tools UI
3: Scroll down with your mouse wheel.

**Comment by AWildErin** [comment] 2023-04-07 17:05
Duplicate of https://github.com/StrataSource/Engine/issues/674

**Closed by AWildErin** 2023-04-07 17:05 UTC
Labels: Type: bug
