### ISSUE TITLE
Bug: Hammer Model Browser 3D preview is broken

### ISSUE THREAD

**Issue by Klunkyone** [StrataSource/Portal-2-Community-Edition#1641] opened 2024-01-20 23:25 UTC
### Describe the bug

Upon opening up the model browser from Hammer and looking at the 3D preview, you will notice that it is broken.
A video is included.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/80126040/d3fd726a-73dc-4d06-8530-7983402f2948

### Issue Map

None

### To Reproduce

1: Open model browser from hammer
2: Select any model
3: Woah! Its screwed up!

**Comment by craftablescience** [comment] 2024-01-20 23:34
Duplicate of https://github.com/StrataSource/Engine/issues/1043 (but thanks for reporting!)

**Closed by craftablescience** 2024-01-20 23:34 UTC
Labels: Type: bug
