### ISSUE TITLE
Bug: sp_a2_bts3 - cannot see even with Wheatley's flashlight on

### ISSUE THREAD

**Issue by ashifolfi** [StrataSource/Portal-2-Community-Edition#956] opened 2022-07-25 00:34 UTC
### Describe the bug

During the escape. after Wheatley turns his flashlight on. the level is still impossible to see?

https://user-images.githubusercontent.com/29577987/180672679-27f204e1-ad51-4dc9-820c-94b665f3a6c3.mp4

Expected behavior:
Wheatley projects a light that is used to light up where he's pointing so you can actually see where you're going

### Issue Map

sp_a2_bts3

### To Reproduce

1. Load up sp_a2_bts3
2. When Wheatley turns his flashlight on you won't be able to see anything despite him supposed to be lighting things up

**Comment by craftablescience** [comment] 2022-07-25 00:41
Duplicate of https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/857

**Comment by craftablescience** [comment] 2022-07-25 00:41
However, this one has more info, so I'll close the old one

**Comment by Equalizer5118** [comment] 2023-11-04 16:48
still happens in current build
![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/113145248/40db7cdb-f217-4c42-9d11-c8e22f1798a1)

**Comment by AWildErin** [comment] 2024-01-20 20:22
This is fixed in latest staging.

**Closed by AWildErin** 2024-01-20 20:22 UTC
Labels: Type: bug, What: Entities, Compat: Portal 2, Priority 2: High, Type: Compat
