### ISSUE TITLE
Portal particle offset

### ISSUE THREAD

**Issue by darvil82** [StrataSource/Portal-2-Community-Edition#364] opened 2020-09-10 23:57 UTC
**(P2:CE)** First of all, this only happened to me once, so it may be hard to replicate. I can only tell that it happened after loading a save (that i saved right before) and placing the portals. (only to the blue portal)
As you can see, the offset does apply to all axis, and it does not reset until you load the save again/restart the map.

![20200911013112_1](https://user-images.githubusercontent.com/48654552/92827331-07eee580-f3d2-11ea-9198-8368f844be8c.jpg)
![20200911013122_1](https://user-images.githubusercontent.com/48654552/92827346-0cb39980-f3d2-11ea-9c13-25ddf7621e30.jpg)
![20200911013148_1](https://user-images.githubusercontent.com/48654552/92827353-0f15f380-f3d2-11ea-94cb-d334724edf36.jpg)
![20200911013204_1](https://user-images.githubusercontent.com/48654552/92827361-10472080-f3d2-11ea-9888-9a35d6f9bf79.jpg)

**Comment by FrozenDragon0** [comment] 2020-09-11 06:53
I've experienced this myself in regular P2 but only in coop playing as p-body.

**Comment by Luke18033** [comment] 2022-12-13 07:28
I haven't noticed this in a long time, might be fixed.

**Comment by ozxybox** [comment] 2024-02-16 07:26
Closing this. The issue is nearly 4 years old, and I haven't seen this issue myself. If you're able to reproduce it, please reopen this issue!

**Closed by ozxybox** 2024-02-16 07:26 UTC
Labels: Type: bug, Compat: Portal 2, What: Graphics, Status: can't reproduce, Type: Compat
