### ISSUE TITLE
Feature: Scalability for funnel and light bridge

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1274] opened 2023-04-21 09:51 UTC
### Which component should be improved?

Gameplay

### Describe your suggestion

(Original idea [here](https://discord.com/channels/663715905267564564/1094505262376816680/1094505262376816680))This being useful for things like coop with tiny bridges sometimes being hard to move on with 2 people or custom funnel models that might be off in size. It's also should create new opportunitys for puzzles.
This should be parameter with output command for dynamic scaling.

**Comment by ozxybox** [comment] 2024-07-17 07:50
Closing as duplicate of both #807 and #808

**Closed by ozxybox** 2024-07-17 07:50 UTC
Labels: Type: Enhancement
