### ISSUE TITLE
Bug: A.I. Disabled in neurotoxin generator map

### ISSUE THREAD

**Issue by ShygalCoco** [StrataSource/Portal-2-Community-Edition#856] opened 2022-04-06 18:10 UTC
### Describe the bug

A.I. Disabled text appears on screen and stops Wheatley from talking in neurotoxin generator map.
![image](https://user-images.githubusercontent.com/69723642/162040289-100b8419-ac9c-457a-8d49-7a8204f001ae.png)

### Issue Map

sp_a2_bts5

### To Reproduce

Go to sp_a2_bts5 and it should happen immediately.

### Operating System

Windows 10

**Comment by FrozenDragon0** [comment] 2022-07-26 06:06
Doesn't seem to occur for me, AI plays like normal.

**Comment by AWildErin** [comment] 2022-07-27 14:33
This does occur but *very* rarely. I've had it happen to me once but I wasn't exactly testing for it then. When I do try and test for it I never seem to encounter it which is a painful experience.

**Comment by whywhywhyw** [comment] 2022-11-15 16:59
I somehow managed to reproduce this problem in hl2.

**Comment by whywhywhyw** [comment] 2022-11-15 17:10
occurs in almost all games that use source.

**Comment by tmob03** [comment] 2023-08-07 06:10
Seems to be fixed on Staging.

**Closed by tmob03** 2023-08-07 06:10 UTC
Labels: Type: bug, Compat: Portal 2, Priority 2: High, Size 4: Small, Type: Compat
