### ISSUE TITLE
Feature: Scalable funnel/light brudges

### ISSUE THREAD

**Issue by pikpik-carrot** [StrataSource/Portal-2-Community-Edition#903] opened 2022-06-09 23:02 UTC
### Which component should be improved?

Entity

### Describe your suggestion

Add a property value that makes the scale that the funnle is at larger or smaller. This could be used to let funnels have more room for error or in some cases prevent cheese.

**Comment by ozxybox** [comment] 2024-07-17 07:45
Closing as duplicate of both #807 and #808

**Closed by ozxybox** 2024-07-17 07:45 UTC
Labels: Type: Enhancement, What: Entities, What: Gameplay, Priority 5: Very Low, Size 4: Small
