### ISSUE TITLE
Gel color customization UI

### ISSUE THREAD

**Issue by AddMGH** [StrataSource/Portal-2-Community-Edition#306] opened 2020-08-04 18:28 UTC
![image](https://user-images.githubusercontent.com/26350889/89330824-b774c180-d688-11ea-94ca-9c5ec9856b8c.png)
![image](https://user-images.githubusercontent.com/26350889/89336677-ad0af580-d691-11ea-9820-3a811dbeb19f.png)

**Comment by distributivgesetz** [comment] 2020-08-04 19:27
Duplicate of #245, please search up issues before spamming issues from the webpage, thanks.

**Comment by AddMGH** [comment] 2020-08-04 19:28
how is the customisation menu a dupe of allowing colors to be changed mid-map???

**Comment by ozxybox** [comment] 2022-06-28 04:38
Closed in favor of using convars https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/245.

**Comment by Luke18033** [comment] 2022-06-28 04:41
This is completely different, the cvars are implemented already, they just need to be added to the UI.

**Comment by Luke18033** [comment] 2023-10-18 00:47
There's already issues on the panorama repo covering this

**Closed by Luke18033** 2023-10-18 00:47 UTC
Labels: Type: enhancement, What: UI
