### ISSUE TITLE
Feature: Add the ability to put stickers on the portalgun 

### ISSUE THREAD

**Issue by Lord-of-Squishe** [StrataSource/Portal-2-Community-Edition#973] opened 2022-08-24 16:00 UTC
### Which component should be improved?

UI/UX

### Describe your suggestion

Add a ui in the portalgun skin changer window for adding custom workshop stickers to the portalgun similar to the weapon sticker system in CSGO.
This could work well with custom skins and would make for some interesting gun customization.

**Comment by ozxybox** [comment] 2024-10-14 08:56
Closing as partially out of scope and partially a duplicate of #119

Very neat idea though!!

**Closed by ozxybox** 2024-10-14 08:56 UTC
Labels: Type: Enhancement, What: Graphics, What: UI, Priority 5: Very Low, Type: Idea/Concept
