### ISSUE TITLE
Feature: Adjustable Rotation Origin

### ISSUE THREAD

**Issue by Lifegivesmelemons** [StrataSource/Portal-2-Community-Edition#1232] opened 2023-04-01 20:35 UTC
### Which component should be improved?

Audio

### Describe your suggestion

An adjustable rotation origin similar to Hammer++'s.

**Comment by tmob03** [comment] 2023-04-01 20:47
Duplicate of https://github.com/StrataSource/Engine/issues/209

**Closed by tmob03** 2023-04-01 20:47 UTC
Labels: Type: enhancement
