### ISSUE TITLE
Feature: Increase Rocket Turret ROF to match Portal 1

### ISSUE THREAD

**Issue by LambdaCore21** [StrataSource/Portal-2-Community-Edition#1637] opened 2024-01-13 00:43 UTC
### Which component should be improved?

npc_rocket_turret

### Describe your suggestion

Popular mods like Portal: Epic Edition rely heavily on the Rocket Turret. It is often used to pressure the player.

In P2CE however it was decided to use the "intended" behaviour of the Rocket Turret which is not present in Portal 1.
![grafik](https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/1775afbe-8899-4cf3-a9d7-afe17bd78eec)

This results in a decreased rate of fire and agressiveness:

https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/e638e2ad-9ba5-4d80-98ef-54a1c1367568

**Comment by LambdaCore21** [comment] 2024-01-13 00:52
[p2ce test map.zip](https://github.com/StrataSource/Portal-2-Community-Edition/files/13925289/p2ce.test.map.zip)

**Comment by LambdaCore21** [comment] 2024-01-14 15:15
![grafik](https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/7e8d65c6-6889-4c3a-ad62-2f3e634d8c15)

**Comment by vrad-exe** [comment] 2024-03-09 00:11
The bug I talked about in that old issue only affects the sounds and is unrelated. This seems to have just been caused by the "lockon time" being increased from 2 to 3 seconds. All of those parameters should probably be configurable by mappers anyway.

**Comment by LambdaCore21** [comment] 2024-03-14 23:17
Maybe with AngelScript, but there's no KeyValue

**Comment by vrad-exe** [comment] 2024-03-14 23:40
They're not currently configurable, I'm saying they should be

**Comment by vrad-exe** [comment] 2024-04-04 21:47
Just realized this is basically a duplicate of #1209

**Comment by craftablescience** [comment] 2024-08-16 07:35
> The bug I talked about in that old issue only affects the sounds and is unrelated. This seems to have just been caused by the "lockon time" being increased from 2 to 3 seconds. All of those parameters should probably be configurable by mappers anyway.

Lockon time is 2 seconds as far as I can tell, maybe this got fixed already?

**Comment by ozxybox** [comment] 2024-08-17 01:19
Fixed by @craftablescience in the next staging build

**Closed by ozxybox** 2024-08-17 01:19 UTC
Labels: Type: Enhancement, What: Entities, What: Gameplay, Priority 4: Low, Compat: Portal 1, Size 5: Trivial, Quality of Life
