### ISSUE TITLE
Switching from portal gun to paint gun breaks wheatley 

### ISSUE THREAD

**Issue by Teapottt** [StrataSource/Portal-2-Community-Edition#1578] opened 2023-11-09 17:52 UTC
### Describe the bug

When your holding wheatley with the portal gun and you switch to the paint gun it leaves him floating in the air
https://github.com/StrataSource/Portal-2-Community-Edition/assets/149398659/68a40f89-4c0d-4f60-bf8d-092a59500e84

### Issue Map

sp_a1_wakeup

### To Reproduce

1. Open sp_a1_wakeup
2. Give your self the paint gun
3. Switch to paint gun

**Comment by MyGamepedia** [comment] 2023-11-09 18:47
Copy of https://github.com/StrataSource/Portal-2-Community-Edition/issues/1171

**Comment by ozxybox** [comment] 2024-06-02 03:27
Thanks for identifying that this is a dupe! Closing as duplicate of #1171

**Closed by ozxybox** 2024-06-02 03:27 UTC
Labels: Type: bug
