### ISSUE TITLE
setang command doesn't work

### ISSUE THREAD

**Issue by rabbix2020** [StrataSource/Portal-2-Community-Edition#1555] opened 2023-10-18 00:03 UTC
### Describe the bug

https://github.com/StrataSource/Portal-2-Community-Edition/assets/67027531/0a801099-8949-4297-af28-5c08d4713434

https://github.com/StrataSource/Portal-2-Community-Edition/assets/67027531/22ff3eeb-ce77-4934-9b94-684f27a727f6

### Issue Map

no matter what's map

### To Reproduce

1. try to type setang 0 90 0
2. see the result that command doesn't work

### Operating System

Windows 10

**Comment by AWildErin** [comment] 2023-10-18 00:08
Duplicate of https://github.com/StrataSource/Engine/issues/244

**Closed by AWildErin** 2023-10-18 00:08 UTC
Labels: Type: bug
