### ISSUE TITLE
Bug: Player can get stuck in wall light

### ISSUE THREAD

**Issue by Doclic** [StrataSource/Portal-2-Community-Edition#1219] opened 2023-03-22 01:52 UTC
### Describe the bug

lbry://uhhhh_i_would_put_a_joke_here_or_sth_but_im_not_funny
If you don't have a lbry client, use [this link](https://odysee.com/@Doclic:0/uhhhh_i_would_put_a_joke_here_or_sth_but_im_not_funny:7)
This 'works' with both Havok physics and Jolt physics

### Issue Map

Triple Laser (maybe other maps too, didn't test)

### To Reproduce

1. Go on Triple Laser
2. Place the portals like on the video
3. Go on the wall (you can walk next to the light)
4. Remove the portal you used to get up there

**Comment by DrPeeper228** [comment] 2023-03-22 06:51
why you don't use youtube?

**Comment by ozxybox** [comment] 2023-03-22 14:47
Possibly related to #1217

**Comment by Doclic** [comment] 2023-03-23 18:30
> why you don't use youtube?

because i don't like youtube

**Comment by Trico-Everfire** [comment] 2023-03-26 20:07
> Possibly related to #1217

It is, those are static props, and when a portal is close, it disables collision. This is a duplicate issue.

**Comment by JJL772** [comment] 2023-03-30 04:35
Duplicate of #1217

**Closed by JJL772** 2023-03-30 04:35 UTC
Labels: Type: bug, Compat: Portal 2, What: Movement, Priority 1: Critical
