### ISSUE TITLE
Bug: ent_create vort_charge_token or  vort_effect_dispel crashes game

### ISSUE THREAD

**Issue by tmob03** [StrataSource/Portal-2-Community-Edition#1311] opened 2023-05-05 02:17 UTC
### Describe the bug

When using `ent_create` to create either of these entitles, the game crashes. These are ents spawned for vortigaunt visual effect so they aren't meant to be spawned this way, but it still shouldn't crash the game.

The `vort_charge_token` may be the cause of #1046 ? It spawns fine in HL2 created this way. `vort_effect_dispel` crashes even in HL2 when spawned this way, though.

### Issue Map

N/A

### To Reproduce

1. Open a map
2. `ent_create` either a  `vort_effect_dispel` or a  `vort_charge_token`
3. Notice crash

### Operating System

Windows 10 Home 19045

**Comment by pivotman319-owo** [comment] 2023-05-06 11:13
Duplicate of #1046; this is related to invalid control points in-engine

**Closed by pivotman319-owo** 2023-05-06 11:13 UTC
Labels: Type: bug, Type: crash, Size 4: Small, Compat: Half-Life 2, Type: Compat

**Comment by tmob03** [comment] 2023-05-06 19:07
@pivotman319-owo `vort_effect_dispel` is too?
