### ISSUE TITLE
Light travels through portals

### ISSUE THREAD

**Issue by Badpoolinator** [StrataSource/Portal-2-Community-Edition#1324] opened 2023-05-13 15:17 UTC
### Which component should be improved?

Gameplay

### Describe your suggestion

I'm just wondering about light travelling through portals. It could probably be used as a mechanic, or just for prettier looking portals.

**Comment by MyGamepedia** [comment] 2023-05-13 16:01
Keep in mind that it's not possible with static lighting (that is 90% of most source engine games). I hope about volumetric light.

**Comment by LilyBorb** [comment] 2023-05-13 20:59
I thought about this too recently, but with projected textures. could look cool but might be performance heavy

**Comment by JVGRYT** [comment] 2023-05-13 21:37
> I thought about this too recently, but with projected textures. could look cool but might be performance heavy

Well, what you could do is make it an option in the settings, so that higher powered PCs can use the feature, but lower powered PCs can turn it off.

**Comment by MyGamepedia** [comment] 2023-05-14 05:05
> > I thought about this too recently, but with projected textures. could look cool but might be performance heavy
> 
> Well, what you could do is make it an option in the settings, so that higher powered PCs can use the feature, but lower powered PCs can turn it off.

Good idea! But should be also parameter that allow light ALWAYS go through, even if option disabled. It's should be for puzzles that use this feature as part of themself.

**Comment by JVGRYT** [comment] 2023-05-14 05:09
> > > I thought about this too recently, but with projected textures. could look cool but might be performance heavy
> > 
> > Well, what you could do is make it an option in the settings, so that higher powered PCs can use the feature, but lower powered PCs can turn it off.
> 
> Good idea! But should be also parameter that allow light ALWAYS go through, even if option disabled. It's should be for puzzles that use this feature as part of themself.

Yeah, good idea. But also, users should be advised to not use this feature too heavily. 
Maybe add a keyvalue in the env_projectedtexture entity that forces this to be on and off, and include a description that says this is GPU expensive and should be used sparingly.

**Comment by MyGamepedia** [comment] 2023-05-14 09:57
Also should never disable this function for player flashlight.

**Comment by JVGRYT** [comment] 2023-05-14 10:33
> Also should never disable this function for player flashlight.

Yeah, when I'm using the flashlight it always seems weird when I go through portals.

**Comment by craftablescience** [comment] 2023-05-27 04:36
Duplicate of #462

**Closed by craftablescience** 2023-05-27 04:36 UTC
Labels: Type: enhancement

**Comment by MyGamepedia** [comment] 2023-05-27 05:41
> Duplicate of #462

It's not include some ideas and volumetric lighting.

**Comment by craftablescience** [comment] 2023-05-27 05:59
Then comment on that issue
