### ISSUE TITLE
Bug: PBR Shader becoming darker and lighter depending on where I am standing.

### ISSUE THREAD

**Issue by JackRHainsworth** [StrataSource/Portal-2-Community-Edition#1647] opened 2024-02-24 16:14 UTC
### Describe the bug

When using a PBR material, the reflections (even without an envmap) become darker and lighter depending on where in the level I am looking at them from. This is most noticeable when moving through portals and seeing the color darken quickly.

### Issue Map

My own styleguide map.

### To Reproduce

Put a PBR material on some brushes in the level.
Look at the material from different angles and positions.

**Comment by Equalizer5118** [comment] 2024-02-24 16:34
duplicate of [#993](https://github.com/StrataSource/Engine/issues/993), already fixed in staging

**Comment by JJL772** [comment] 2024-02-24 17:11
Thanks for reporting, but yeah, this was fixed on staging and has not yet been released to beta testers.

**Closed by JJL772** 2024-02-24 17:11 UTC
Labels: Type: bug
