### ISSUE TITLE
Half-Life 2 Bug: Airboat is tilted forward in water

### ISSUE THREAD

**Issue by MarcusKubis9** [StrataSource/Portal-2-Community-Edition#1674] opened 2024-03-16 08:41 UTC
### Describe the bug

title

might be worth trying loading into a map where the airboat doesn't start in the water

https://www.youtube.com/watch?v=lJvV4ABHXps&t=1s

### To Reproduce

Go to any map with the Airboat and drive around in water

**Comment by craftablescience** [comment] 2024-03-16 08:43
Duplicate of #1416

**Closed by craftablescience** 2024-03-16 08:43 UTC
Labels: Type: bug, Compat: Half-Life 2
