### ISSUE TITLE
Feature: The ability to resize funnels and light bridge width/height.

### ISSUE THREAD

**Issue by pikpik-carrot** [StrataSource/Portal-2-Community-Edition#1223] opened 2023-03-29 00:33 UTC
### Which component should be improved?

Gameplay

### Describe your suggestion

The ability to change the width and height of funnels and light bridges to make them larger than usual.

**Comment by ozxybox** [comment] 2024-07-17 07:59
Closing as duplicate of both #807 and #808

**Closed by ozxybox** 2024-07-17 07:59 UTC
Labels: Type: Enhancement
