### ISSUE TITLE
Portal 2 Bug: Wheatley disappears after entering the stalemate resolution annex in `sp_a4_finale4`

### ISSUE THREAD

**Issue by Equalizer5118** [StrataSource/Portal-2-Community-Edition#1574] opened 2023-11-04 18:37 UTC
### Describe the bug

After entering the trapped button room, wheatley disappears. This lasts all the way until the scene is over and you are then teleported to the room where GLaDOS wakes you up with P-Body and Atlas.

Space core also does not appear to bonk wheatley when you are holding onto him through the portal to the moon.

![20231104112439_1](https://github.com/StrataSource/Portal-2-Community-Edition/assets/113145248/c2315496-ed13-4ad9-9676-ec30f729f18a)
![20231104112446_1](https://github.com/StrataSource/Portal-2-Community-Edition/assets/113145248/90c7995c-76be-43fa-b572-a207994d982e)
![20231104112508_1](https://github.com/StrataSource/Portal-2-Community-Edition/assets/113145248/778f19b5-3f9f-48ff-b3e1-83d6fc26537a)
![20231104112515_1](https://github.com/StrataSource/Portal-2-Community-Edition/assets/113145248/bf04deb1-b512-4750-a455-1e4fdd6966bf)
![20231104112525_1](https://github.com/StrataSource/Portal-2-Community-Edition/assets/113145248/4cc051e3-a184-400a-851f-331980c17c7e)

### To Reproduce

1. Open `sp_a4_finale4`
2. Beat wheatley
3. portal into the Stalemate Resolution Annex
4. Observe bug

### Operating System

Tested on Windows 11

**Comment by FrozenDragon0** [comment] 2023-11-05 00:31
This is a duplicate of https://github.com/StrataSource/Portal-2-Community-Edition/issues/208

**Closed** 2023-11-06 23:32 UTC
Labels: Type: bug, Compat: Portal 2
