### ISSUE TITLE
Feature: prop_tractor_beam and trigger_tractorbeam improvements.

### ISSUE THREAD

**Issue by Trico-Everfire** [StrataSource/Portal-2-Community-Edition#1213] opened 2023-02-27 13:32 UTC
### Which component should be improved?

Entity

### Describe your suggestion

prop_tractor_beam and trigger_tractorbeam are point/brush entities responsible for making funnels work. However, they're a bit limited, trigger_tractorbeam doesn't even have a FGD entry, not even valve developer wiki doesn't have an entry on it. despite it being a pretty cool entity. prop_tractor_beam is already quite a packed entity, but lacks the ability to pass through a filter to the trigger_tractorbeam it creates.

This feature request is 2 things:
1: trigger_tractorbeam receiving it's own FGD entry, as well as the customizability of prop_tractor_beam.
2: prop_tractor_beam to have a filter passthrough to exclude/include entities, as currently it picks up everthing + physics debris.

**Comment by Equalizer5118** [comment] 2023-02-27 21:05
There isnt an entry on the vdc for that? Huh. That will change soon

**Comment by TeamSpen210** [comment] 2023-02-27 21:05
It's trigger_tractorbeam, actually.

**Comment by ozxybox** [comment] 2024-07-17 08:01
Closing as duplicate of both #807 and #808
Issue #807 does not mention trigger_tractorbeam, but that conversation can be migrated to there.

**Closed by ozxybox** 2024-07-17 08:01 UTC
Labels: Type: Enhancement
