### ISSUE TITLE
Look trigger acts differently to base Portal 2

### ISSUE THREAD

**Issue by incxs2** [StrataSource/Portal-2-Community-Edition#1035] opened 2022-09-17 17:00 UTC
Ceiling catapult speedrun route is not possible due to a look trigger activating in P2CE whereas it doesn't in base game

Expected behaviour: 0:19 in this video - https://www.youtube.com/watch?v=qjR0dIqcOFs

Actual behaviour - panels above lower after going through the portal - https://cdn.discordapp.com/attachments/829077608742125648/1020343109575524472/Desktop_2022.09.16_-_15.38.34.02.mp4

**Comment by ozxybox** [comment] 2024-06-28 03:54
Duplicate of https://github.com/StrataSource/Engine/issues/1034
Also fixed in the next staging build

**Closed by ozxybox** 2024-06-28 03:54 UTC
Labels: Type: Bug, What: Entities, What: Gameplay, Compat: Portal 2, Priority 3: Medium, Focus: Speedrunning, Type: Compat
