### ISSUE TITLE
Bug: Laser going through walls glitch in coop

### ISSUE THREAD

**Issue by ShygalCoco** [StrataSource/Portal-2-Community-Edition#1459] opened 2023-07-21 19:16 UTC
### Describe the bug

This image best describes the bug. P-body portals on the wall beside is not necessary.
![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/69723642/5c5aa682-2788-4dd3-beee-72e58392e976)

### Issue Map

Map in image.

### To Reproduce

Open map seen in image and place portals infront and behind the first wall.

### Operating System

Windows 10

**Comment by MyGamepedia** [comment] 2023-07-21 19:19
?We already have this https://github.com/StrataSource/Portal-2-Community-Edition/issues/1250? ?Duplicate?

**Comment by AWildErin** [comment] 2023-07-21 19:20
Duplicate of #1250

**Comment by MyGamepedia** [comment] 2023-07-21 19:20
And also... it is func_detail of brush model ?

**Closed by AWildErin** 2023-07-21 19:20 UTC
Labels: Type: bug
