### ISSUE TITLE
Allow projected walls and tractor beams to be recoloured

### ISSUE THREAD

**Issue by RealityAnomaly** [StrataSource/Portal-2-Community-Edition#286] opened 2020-07-30 08:09 UTC
- [x] Recolourable tractor beams
- [ ] Recolourable projected walls

Allow both to be recoloured. Should be possible with primarycolour/secondarycolour keyvalues and corresponding I/O inputs.

**Comment by SpyceTewan** [comment] 2020-07-30 12:02
I add this as a SetColor and ResetColor input.

**Comment by Luke18033** [comment] 2023-04-28 01:48
Funnels are colorable now, why not light bridges still?

**Comment by ozxybox** [comment] 2024-07-17 07:15
Closing as duplicate of both #807 and #808 
This was also partially implemented but is incomplete.

**Closed by ozxybox** 2024-07-17 07:15 UTC
Labels: Type: Enhancement, What: Entities
