### ISSUE TITLE
Bug: Important models disappear during the final boss cutscene

### ISSUE THREAD

**Issue by Wolfcl0ck** [StrataSource/Portal-2-Community-Edition#1655] opened 2024-02-24 21:50 UTC
### Build Information
**Chaos.exe Build Date:** 06-11-2023 22:13:42 UTC
**Server Build Date:** 06-11-2023 22:24:40 UTC
**Client Build Date:** 06-11-2023 22:24:41 UTC
**Branch:** Default, using Panorama UI

### Hardware Information
**CPU:** AMD Ryzen 9 3900X 12-Core Processor 3.80 GHz
**GPU:** 4095MB NVIDIA GeForce RTX 2070 (EVGA)
**RAM:** 32 GB DDR4 RAM, 2x 16 GB Corsair

### Bug Information
During the end of the Wheatley Boss fight, Wheatley's model, Wheatley's body, the corrupted cores, and the claw that drags Glados' head all disappear. Was reproduceable between multiple launches of the game.

### Additional Potential Factors
"cl_portal_crosshair_mode" was set to 1
Game is running in Borderless Windowed mode
Game is running with -multirun enabled
Game is running with -insecure enabled

### Footage

https://github.com/StrataSource/Portal-2-Community-Edition/assets/16748747/39f99787-e1a1-4dcb-96af-34fe9e19bf87

https://github.com/StrataSource/Portal-2-Community-Edition/assets/16748747/950e86de-0751-490a-a916-619b828c28c1
![20240224143339_1](https://github.com/StrataSource/Portal-2-Community-Edition/assets/16748747/74744472-3f25-407b-83f4-52657f86ac86)

### Issue Map

sp_a4_finale4

### To Reproduce

1. Open sp_a4_finale4
2. Beat Wheatley
3. The aforementioned models will disappear

### Operating System

Windows 10 Home 64-bit, build 19045.3570

**Comment by FrozenDragon0** [comment] 2024-02-25 05:13
This would be a duplicate of https://github.com/StrataSource/Portal-2-Community-Edition/issues/208

**Comment by vrad-exe** [comment] 2024-03-11 00:39
Yeah this is a longstanding issue which I think has to do with culling iirc?

**Comment by pivotman319-owo** [comment] 2024-06-07 21:53
Duplicate of StrataSource/Engine#1150. Root cause documented [here](https://github.com/StrataSource/Engine/issues/1150#issuecomment-2099325097).

Closing to facilitate further discussion onto original issue.

**Closed by pivotman319-owo** 2024-06-07 21:53 UTC
Labels: Type: Bug, Compat: Portal 2, What: Graphics
