### ISSUE TITLE
Feature: Show current map in console

### ISSUE THREAD

**Issue by Doclic** [StrataSource/Portal-2-Community-Edition#1222] opened 2023-03-24 00:05 UTC
### Which component should be improved?

UI/UX

### Describe your suggestion

Title says it all

This is already done in Portal 2 VGUI
![image](https://user-images.githubusercontent.com/30270428/227390637-010ad8ef-b792-4ca0-8bcf-1eed51b83b87.png)

**Comment by DarviL82** [comment] 2023-03-24 00:08
Duplicate of #359.

**Closed by DarviL82** 2023-03-24 00:08 UTC
Labels: Type: enhancement
