### ISSUE TITLE
Feature: More Lightbridge Options

### ISSUE THREAD

**Issue by ErinRoseWebs69** [StrataSource/Portal-2-Community-Edition#792] opened 2022-01-12 13:37 UTC
### Which component should be improved?

Entity

### Describe your suggestion

-change bridge color
-change bridge texture

### Expected result

kinda obvious lol. if i missed a feature someone wants, i can edit this.

**Comment by ozxybox** [comment] 2024-07-17 07:11
Closing as duplicate of #808

**Closed by ozxybox** 2024-07-17 07:11 UTC
Labels: Type: Enhancement, What: Entities
