### ISSUE TITLE
Bug: Edges of Water Reflection are Broken on "sp_a2_trust_fling"

### ISSUE THREAD

**Issue by Rip-Rip-Rip** [StrataSource/Portal-2-Community-Edition#1473] opened 2023-07-31 18:40 UTC
### Describe the bug

The edges of the dynamic reflection inside the water appear white and broken. The screenshots show it happening on "sp_a2_trust_fling". I have only noticed it on this map so far, but it may appear in other maps.

![water reflection bug - p2 image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/140695311/3acac911-4da0-42cc-881e-5c359290d1e8) ![water reflection bug - p2ce image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/140695311/7fd847d8-b383-44cd-a2ab-d8562c65f624)

### Issue Map

sp_a2_trust_fling, but may occur in other maps.

### To Reproduce

1. Open sp_a2_trust_fling.
2, Observe water.

### Operating System

Windows 11 Build 22621.1992

**Comment by ozxybox** [comment] 2023-08-10 16:16
Closing as a duplicate of https://github.com/StrataSource/Engine/issues/614

**Closed by ozxybox** 2023-08-10 16:16 UTC
Labels: Type: bug, What: Graphics
